# Generated by Django 5.0 on 2024-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='restaurant',
            field=models.CharField(choices=[('Carnes', 'Carnes'), ('Pescados', 'Pescados'), ('Típicos', 'Típicos')], default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
